#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /home/ubuntu/hello.html
echo "Ceci n'est pas une page
" > /var/www/html/404.html
hostname=$(hostname)
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $hostname;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    error_page 404 /404.html;
    location = /404.html {
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart#!/usr/bin/env bash
# Install nginx web server
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" > /home/ubuntu/hello.html
echo "Ceci n'est pas une page
" > /var/www/html/404.html
hostname=$(hostname)
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $hostname;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    
    error_page 404 /404.html;
    location = /404.html {
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
