#!/usr/bin/env bash
# This Script explains PID
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "/var/run/myscript.pid"; exit 0' SIGQUIT
trap 'echo "I hate the kill command"; rm "/var/run/myscript.pid"; exit 0' SIGTERM
echo "$$" > "/var/run/myscript.pid"
while true
do
	echo "To infinity and beyond"
	sleep 2
done