#!/usr/bin/env bash
# This Script explains PID

if [ "$1" = "start" ] ; then
    ./manage_my_process &
    echo "$!" > "/var/run/my_process.pid"
    echo "manage_my_process started"
elif [ "$1" = "stop" ] ; then
    PID=$(<"/var/run/my_process.pid")
    rm "/var/run/my_process.pid"
    kill "$PID"
    echo "manage_my_process stopped"
elif [ "$1" = "restart" ] ; then
    rm "/var/run/my_process.pid"
    ./manage_my_process &
    echo "$!" > "/var/run/my_process.pid"
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi