#!/usr/bin/env bash
# This Script is to show how for loops work


for (( i=1; i<=100; i++ ))
do
	
	if (( i%3==0 && i%5==0 ))    # ← see 'man bash' for valid conditional statements.
	then
		echo "FizzBuzz"
	elif ((i%3==0))
	then
		echo "Fizz"
	elif ((i%5==0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	
done
