#!/usr/bin/env bash
# This Script is to show how while loops work

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		
	echo "bad luck"
	elif [ $i -eq 8 ]; then
	echo "good luck"
	else
	echo "Best School"
		
	fi
	((i++))  # ← put the command that you want to run on each line here
done
