#!/usr/bin/env bash
# This Script is to show how while loops work

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	
	minutes=1
	while [ $minutes -le 59 ]
	do
	echo "$minutes"
		    
	((minutes++)) 
	done
	((hour++)) 
done
