#!/usr/bin/env bash
# This Script is to show how for loops work

file_name=school

if [ -e "$file_name" ]; then
    echo "$file_name file exists"

    # Check if the file is empty
    if [ -s "$file_name" ]; then
        echo "$file_name file is not empty"
    else
        echo "$file_name file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$file_name" ]; then
        echo "$file_name is a regular file"
    fi
else
    echo "$file_name file does not exist"
fi
